on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'PopApis/PopApis'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore PopApis/PopApis.sln
      - name: Build and publish APIs
        run: |
          dotnet build '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/PopApis.csproj' 
          dotnet publish '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/PopApis.csproj' -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: pencilsofpromise
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}